### ISSUE TITLE
錯誤的修正

### ISSUE THREAD

**Issue by wayne930242** [g0v/laweasyread-front#24]
http://t17.techbang.com/topics/24550

標題的「[分享] 台灣的年輕人，你除了創業，沒有第二條路了！」被修成「[分享] 台灣的年輕人，你除了創業，沒有§2路了！」

**Comment by kong0107** [comment]
於 1.1.1 版修正，在整個頁面都沒有比對到法規名稱的情形，不轉換條號。
另外，也可於選項頁面中，指定條號的轉換方式。
