### ISSUE TITLE
chrome版僅是mouseover就會跳轉視窗

### ISSUE THREAD

**Issue by fringetree** [g0v/laweasyread-front#30]
如[截圖](https://imgur.com/a/kHJcG)所示的內嵌視窗只能持續1～2秒。
在法規連結上mouseover大約1～2秒（這期間會顯示內嵌視窗）後，整個頁面會自動跳轉至內嵌視窗的顯示內容，必須用上一頁回到原頁面，但這樣不利於對照，也無法借按鍵輔助改成另開新分頁。

我的chrome是：版本 61.0.3163.100 (正式版本) (64 位元)
是mac版的，不曉得會不會與PC版有差異。

**Comment by kong0107** [comment]
已於 1.0 版修正此問題，不再內嵌全國法規資料庫的網頁。
