### ISSUE TITLE
全國法規資料庫中的條文項次標示被截斷

### ISSUE THREAD

**Issue by swattw** [g0v/laweasyread-front#32]
![image](https://user-images.githubusercontent.com/19372998/50645944-d0e6f080-0faf-11e9-8b88-6bb9ab36efdc.png)
在新版的法務部法規資料庫裡，第三個I不會顯示。

**Comment by kong0107** [comment]
感謝回報 :D
已於 1.4.1 版修正此問題，並已更新至兩大瀏覽器外掛平台。
